services:
  bd:
    build: ./db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    networks:
      - backnet

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontnet
      - backnet
    depends_on:
      - web
      - api

  web:
    image: node:lts
    restart: unless-stopped
    depends_on:
      - bd
    ports:
      - 3000:3000
    networks:
      - backnet
    volumes:
      - ./web:/app
    working_dir: /app
    command: npm start

  api:
    build: ./api
    restart: unless-stopped
    depends_on:
      - bd
    expose:
      - 80
    networks:
      - backnet
    volumes:
      - ./api:/var/www/html

  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    expose:
      - 80
      - 443
    depends_on:
      - bd
    networks:
      - backnet
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password

networks:
  frontnet:
    driver: bridge
  backnet: